#!/bin/bash
APACHE2=$(dpkg-query -W -f='{status}' apache2>/dev/null | grep -c "ok installed")

if [ $APACHE2 -eq 0 ]; then
	echo "Paigaldame apache2"
	apt-get install -y apache2;
elif [ $APACHE2 -eq 1 ]; then
	echo "Apache2 on paigaldatud"
	service apache2 status
fi
